# Generated by Django 5.2.6 on 2025-09-11 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("token", models.CharField(max_length=255)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_command", models.TextField(blank=True, null=True)),
                ("command_id", models.UUIDField(blank=True, null=True)),
                ("last_output", models.TextField(blank=True, null=True)),
                ("system_info", models.JSONField(blank=True, default=dict)),
                ("is_streaming", models.BooleanField(default=False)),
                ("stream_type", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "کلاینت",
                "verbose_name_plural": "کلاینت\u200cها",
                "db_table": "root_client",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ClientActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("command", "دستور"),
                            ("connection", "اتصال"),
                            ("stream", "استریم"),
                            ("file", "فایل"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="root.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت کلاینت",
                "verbose_name_plural": "فعالیت\u200cهای کلاینت",
                "db_table": "root_client_activity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعیه"),
                            ("success", "موفقیت"),
                            ("warning", "هشدار"),
                            ("error", "خطا"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="root.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "db_table": "root_notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
