# Generated by Django 5.2.6 on 2025-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("command", "دستور"),
                    ("connection", "اتصال"),
                    ("stream", "استریم"),
                    ("file", "فایل"),
                    ("keylogger", "کی\u200cلاگر"),
                    ("other", "سایر"),
                ],
                max_length=20,
            ),
        ),
    ]
